[package]
name = "erc721"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false }
ink_lang = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6", default-features = false, features = ["derive"], optional = true }

metis_lang = { git = "https://github.com/patractlabs/metis", default-features = false }
metis_erc721 = { git = "https://github.com/patractlabs/metis", default-features = false }


[lib]
name = "erc721"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    "metis_lang/std",
    "metis_erc721/std",
]
ink-as-dependency = []
